thuchanh/ThuchanhPTUDW/Controllers/GiohangController.cs
using MyClass.DAO;
using MyClass.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThuchanhPTUDW.Library;
using UDWThuchanhPTUDW.Library;

namespace ThuchanhPTUDW.Controllers
{
    public class GiohangController : Controller
    {
        ProductDAO productsDAO = new ProductDAO();
        XCart xcart = new XCart();
        // GET: Cart
        public ActionResult Index()
        {
            //da co thong tin trong gio hang, lay thong tin cua session -> ep  kieu ve list 
            List<CartItem> list = xcart.GetCart();
            return View("Index", list);
        }

        //////////////////////////////////////////////////////////////////
        ///Them vao gio hang
        public ActionResult AddCart(int productid)
        {
            Products products = productsDAO.getRow(productid);
            CartItem cartitem= new CartItem(products.Id, products.Name, products.Image, products.Price, 1);
            //Them vao gio hang voi danh sách list phan tu = Session = MyCart
            XCart xcart = new XCart();
            List<CartItem> list = xcart.AddCart(cartitem, productid);
            //chuyen huong trang
            return RedirectToAction("Index", "Giohang");
        }

        //////////////////////////////////////////////////////////////////
        ///DelCart
        public ActionResult CartDel(int productid)
        {
            xcart.DelCart(productid);
            return RedirectToAction("Index", "Giohang");
        }

        //////////////////////////////////////////////////////////////////
        ///CartUpdate
        public ActionResult CartUpdate(FormCollection form)
        {
            if (!string.IsNullOrEmpty(form["capnhat"]))//nut ThemCategory duoc nhan
            {
                var listamount = form["amount"];
                //chuyen danh sach thanh dang mang: vi du 1,2,3,...
                var listarr = listamount.Split(',');//cat theo dau ,
                xcart.UpdateCart(listarr);
            }
            return RedirectToAction("Index", "Giohang");
        }

        //////////////////////////////////////////////////////////////////
        ///CartUpdate
        public ActionResult CartDelAll()
        {
            xcart.DelCart();
            return RedirectToAction("Index", "Giohang");
        }
    }
}

thuchanh/ThuchanhPTUDW/Controllers/SiteController.cs
using MyClass.DAO;
using MyClass.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace THPTUDWeb.Controllers
{
    public class SiteController : Controller
    {
        LinkDAO linksDAO = new LinkDAO();
        // GET: Site
        public ActionResult Index(string slug = null)
        {
            if (slug == null)
            {
                //chuyen ve trang chu
                return this.Home();
            }
            else
            {
                //tim slug co trong bang link
                Links links = linksDAO.getRow(slug);
                //kiem tra slug co ton tai trong bang Links hay khong
                if (links != null)
                {
                    //lay ra Type trong bang link
                    string typelink = links.Type;
                    switch (typelink)
                    {
                        case "category":
                            {
                                return this.ProductCategory(slug);
                            }
                        case "topic":
                            {
                                return this.PostTopic(slug);
                            }
                        case "page":
                            {
                                return this.PostPage(slug);
                            }
                        default:
                            {
                                return this.Error404(slug);
                            }
                    }
                }
                else
                {
                    //slug khong co trong bang Links
                    //slug co trong bang product?
                    //slug co trong bang Post voi PostType==post?
                    ProductDAO productsDAO = new ProductDAO();
                    PostDAO postsDAO = new PostDAO();

                    //tim slug co trong bang Products
                    Products products = productsDAO.getRow(slug);
                    if (products != null)
                    {
                        return this.ProductDetail(products);
                    }
                    else
                    {
                        //truong hop la Post
                        Posts posts = postsDAO.getRow(slug);
                        if (posts != null)
                        {
                            return this.PostDetail(posts);
                        }
                        else
                        {
                            return this.Error404(slug);
                        }
                    }
                }
            }
        }
        /////////////////////////////////////////////////////////////////////////////
        //Trang chu
        public ActionResult Home()
        {
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            List<Categories> list = categoriesDAO.getListByPareantId(0);
            return View("Home", list);
        }
        //Site/Product
        public ActionResult Product()
        {
            return View("Product");
        }
        public ActionResult Post()
        {
            return View("Post");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/ProductCategory
        public ActionResult ProductCategory(string slug)
        {
            return View("ProductCategory");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/PostTopic
        public ActionResult PostTopic(string slug)
        {
            return View("PostTopic");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/PostPage
        public ActionResult PostPage(string slug)
        {
            return View("PostPage");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/Error404
        public ActionResult Error404(string slug)
        {
            return View("Error404");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Product/Details
        public ActionResult ProductDetail(Products products)
        {
            return View("ProductDetail");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Post/Details
        public ActionResult PostDetail(Posts posts)
        {
            return View("PostDetail");
        }
        
        public ActionResult Gioithieu()
        {
            return View();
        }
        public ActionResult Dangnhap()
        {
            return View();
        }
        public ActionResult Dangky()
        {
            return View();
        }
    }
}

thuchanh/ThuchanhPTUDW/Views/Giohang/Index.cshtml
@model IEnumerable<UDWThuchanhPTUDW.Library.CartItem>

@{
    ViewBag.Title = "Giỏ hàng";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Main content -->
    <section class="content my-2">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <strong class="text-danger">DANH SÁCH GIỎ HÀNG</strong>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if (Model != null)
                {
                    using (Html.BeginForm("CartUpdate", "Giohang", FormMethod.Post))
                    {
                        <table class="table table-bordered table-striped" id="myTable">
                            <thead>
                                <tr>
                                    <th>Sản phẩm</th>
                                    <th style="width:100px;">Hình ảnh</th>
                                    <th>Số lượng</th>
                                    <th>Đơn giá</th>
                                    <th>Thành tiền</th>
                                    <th>Chức năng</th>
                                </tr>
                            </thead>

                            <tbody>
                                @{ decimal tongtien = 0;}
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Name </td>
                                        <td><img src="~/Public/img/product/@item.Img" alt="Img" class="img-fluid" /></td>
                                        <td class="card-product__price"><input name="amount" value="@item.Ammount" type="number" min="1" /></td>
                                        <td class="card-product__price">@string.Format("{0:0,0}", @item.Price)<sup>đ</sup></td>
                                        <td class="card-product__price">@string.Format("{0:0,0}", @item.Total)<sup>đ</sup></td>
                                        <td><a href="@Url.Action("CartDel", "Giohang", new { productid = @item.ProductId })" class="btn-sm btn-danger"> <i class="fa fa-trash"></i></a></td>
                                    </tr>
                                    tongtien += item.Total;
                                }
                                <tr>
                                    <td colspan="3">
                                        <a href="@Url.Action("Index", "Site")" class="btn-sm btn-success"> <i class="fa fa-plus"></i>Mua thêm sản phẩm</a>
                                        <input class="btn-sm btn-info" name="capnhat" value="Cập nhật đơn hàng" type="submit" />
                                        <a href="@Url.Action("CartDelAll", "Giohang")" class="btn-sm btn-danger"> <i class="fa fa-trash-alt"></i> Xóa đơn hàng</a>
                                        <a href="@Url.Action("ThanhToan", "Giohang")" class="btn-sm btn-dark"> <i class="fa fa-paypal"></i> Thanh toán</a>
                                    </td>
                                    <td>Thành tiền</td>
                                    <td colspan="1">@string.Format("{0:0,0}", tongtien)<sup>đ</sup></td>
                                </tr>
                            </tbody>
                        </table>
                    }
                }
                else
                {
                    <h1> Không có sản phẩm trong giỏ hàng </h1>
                }
            </div><!-- /.card-body -->
        </div><!-- /.card -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->